### ISSUE TITLE
The doc links are broken

### ISSUE THREAD

**Issue by scharf** [phosphorjs/phosphor#265] opened 2017-05-18 14:07 UTC
The links  on http://phosphorjs.github.io/phosphor/docs.html are broken (404). For example: http://phosphorjs.github.io/phosphor/api/widgets/globals.html

**Comment by sccolbert** [comment] 2017-05-18 14:12
Duplicate of #203

**Closed** 2017-05-18 14:13 UTC
Labels: Documentation, duplicate

**Comment by sccolbert** [comment] 2017-05-18 14:14
Thanks for the report! We hope to have this fixed soon.

**Comment by sccolbert** [comment] 2017-05-18 21:18
Fixed in #266.
